### ISSUE TITLE
Setting not translated

### ISSUE THREAD

**Issue by KRens** [wbbaddons/JCoins#51]
In de.xml you use following string:
<item name="wcf.user.notification.de.joshsboard.wcf.jcoins.transfer.notification.jCoinsTransfer">
In en.xml you use following string:
<item name="wcf.user.notification.de.joshsboard.wcf.jcoins.transfer.notification.JCoinsTransfer">

The capital j is wrong in en.xml
This results in the variable not being translated properly.

The correct string is:
<item name="wcf.user.notification.de.joshsboard.wcf.jcoins.transfer.notification.jCoinsTransfer">

**Comment by joshuaruesweg** [comment]
This is fixed in JCoins 2.0 which is aviable soon on WCFLsbs.de
